version: '3.9'
services:
  api-php:
    build: .
    command: php -S api-php:8000 -t public 
    container_name: api-php
    volumes:
      - .:/app
      - /app/vendor/
    ports:
      - "8000:8000"
    networks:
      - net-pp
    restart: always
    depends_on:
      - mysql

  mysql:
    env_file: .env
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - net-pp
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - net-pp

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    # volumes:
    #   - ./rabbitmq/data/:/var/lib/rabbitmq/
    #   - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
        - net-pp

networks:
  net-pp:
    driver: bridge